### ISSUE TITLE
app_secret not required

### ISSUE THREAD

**Issue by clarkewing** [benjamincrozat/laravel-dropbox-driver#1]
Hello !

First off, thanks for this package, it's a real lifesaver!

When using it though, I encountered an error:
```
TypeError: Argument 2 passed to Spatie\Dropbox\Client::__construct() must be an instance of GuzzleHttp\Client or null, string given, called in /vendor/benjamincrozat/laravel-dropbox-driver/src/ServiceProvider.php on line 21
```

I read through the source of spatie/dropbox-api, and I believe the app_secret is not required, but only the Oauth2 token. I tested out my theory by setting `'app_secret' => null,` in my `config\filesystems.php` file and it worked!

**Comment by benjamincrozat** [comment]
Hello, you're totally right! I have no idea why, but it works. I released a new version removing the need for the app_secret. Those who configured it in their .env file will not be affected. Thanks!

**Comment by clarkewing** [comment]
Terrific! Thanks for your responsiveness!!
