### ISSUE TITLE
How get absolute link to uploaded file

### ISSUE THREAD

**Issue by mejison** [benjamincrozat/laravel-dropbox-driver#3]
$filename = 'uploads/4p4pr8cs2kFIwk7KSuRKbexEsHxTEjOmXY2qEyAW.jpeg';
Storage::disk('dropbox')->url($filename);

![image](https://user-images.githubusercontent.com/10352363/39924551-f1c08e36-5530-11e8-9e0c-09bfc9427944.png)

**Comment by benjamincrozat** [comment]
Here's the current way to do that:

```php
Storage::disk('dropbox')
    ->getDriver() // `\League\Flysystem\Flysystem` instance
    ->getAdapter() // `\Spatie\FlysystemDropbox\DropboxAdapter` instance
    ->getClient() // `\Spatie\Dropbox\Client` instance
    ->createSharedLinkWithSettings('path/to/your/file');
```

If you want a less verbose way to do that, you should take a look at this issue and send a PR: https://github.com/spatie/flysystem-dropbox/issues/12

My package is just a simple service provider that adds a Dropbox driver to the storage. :)

**Comment by mejison** [comment]
@benjamincrozat Driver Dropbox can replace AWS S3?

**Comment by benjamincrozat** [comment]
@mejison Nope. :) You'll have to ask Google to learn more.

**Comment by MikeLogovi** [comment]
![Capture d’écran 2020-05-19 à 6 43 46 PM](https://user-images.githubusercontent.com/40324123/82359766-4108e180-9a00-11ea-8735-5a6c6bd67310.png)
