### ISSUE TITLE
Dropbox-API-Path-Root

### ISSUE THREAD

**Issue by nielsvr** [benjamincrozat/laravel-dropbox-driver#4]
Is it possible with this package to set the Dropbox-API-Path-Root header? You need this to access Team Shared folders. You add a header to your request with the correct namespace_id, example;

`['Dropbox-API-Path-Root' => '{".tag": "namespace_id", "namespace_id": "1234"}' ];`

Can't seem to find a method for this.

**Comment by benjamincrozat** [comment]
Seems like it's the job of one of Spatie's underlying packages. :)
